// app/page.tsx
"use client";

import { motion, useScroll, useTransform } from "framer-motion";
import {
  ImageIcon,
  Wand2,
  ArrowRight,
  Globe2,
  MessageSquareText,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";

import { Badge } from "@/components/ui/badge";
import { FadeIn } from "@/components/animations/FadeIn";
import { FloatingElement } from "@/components/animations/FloatingElement";
import {
  ProcessStep,
  TestimonialCard,
  FeatureCard,
} from "@/components/story/Card";
import Link from "next/link";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const features = [
  {
    icon: <Wand2 className="h-8 w-8" />,
    title: "AI Magic",
    description:
      "Advanced algorithms that understand context and create compelling narratives",
  },
  {
    icon: <Globe2 className="h-8 w-8" />,
    title: "Multiple Languages",
    description:
      "Generate stories in various languages to reach a global audience",
  },
  {
    icon: <MessageSquareText className="h-8 w-8" />,
    title: "Custom Tone",
    description: "Adjust the storytelling style to match your brand voice",
  },
];

const testimonials = [
  {
    quote:
      "This tool has revolutionized how I create content for my blog. The stories it generates are incredibly engaging.",
    author: "Sarah Johnson",
    role: "Content Creator",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_1.png",
  },
  {
    quote:
      "As an educator, I use this daily to create engaging materials for my students. It's been a game-changer.",
    author: "Michael Chen",
    role: "Education Professional",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_2.png",
  },
  {
    quote:
      "The quality of the generated stories is consistently high. It saves me hours of work every week.",
    author: "Emma Davis",
    role: "Marketing Manager",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_3.png",
  },
];

const faqData = [
  {
    question: "What is StorySnap?",
    answer:
      "StorySnap is an AI-powered platform that transforms your photos into engaging stories. Using advanced artificial intelligence, we help you create compelling narratives from your images with just a few clicks. Whether you're a content creator, business owner, or just someone who loves sharing stories, StorySnap makes it easy to bring your photos to life.",
  },
  {
    question: "How does StorySnap work?",
    answer:
      "Using StorySnap is simple: 1) Upload your photo to our platform. 2) Our AI analyzes your image and generates a unique story based on its contents. 3) Customize and edit the generated story to match your voice and style. 4) Share your story with your audience across various platforms. The entire process takes just minutes, and our AI ensures each story is unique and engaging.",
  },
  {
    question: "Is StorySnap free to use?",
    answer:
      "StorySnap offers both free and premium plans. With our free plan, you can create basic stories and access essential features. Our premium plans unlock advanced features like custom branding, higher resolution outputs, priority processing, and unlimited story generation. Visit our pricing page to learn more about our plans and choose the one that best fits your needs.",
  },
  {
    question: "What types of photos work best with StorySnap?",
    answer:
      "StorySnap works with virtually any type of photo, but the best results come from clear, high-quality images that tell a story or capture a moment. This could include travel photos, event pictures, product images, or personal memories. Our AI is trained to recognize and interpret a wide range of subjects, scenes, and emotions.",
  },
  {
    question: "Can I edit the stories generated by StorySnap?",
    answer:
      "Yes! While our AI creates compelling initial stories, you have full control over the final content. You can edit the text, adjust the tone, add personal details, and customize the story to perfectly match your vision. Our editor is user-friendly and includes features like tone adjustment, length control, and style customization.",
  },
];

export default function HomePage() {
  return (
    <main className="min-h-screen relative bg-gradient-to-b from-primary/5 via-background to-background">
      <div className="relative">
        {/* Floating Decorative Elements */}
        <FloatingElement className="absolute top-20 left-[10%] w-24 h-24 bg-primary/10 rounded-full blur-xl" />
        <FloatingElement className="absolute top-40 right-[15%] w-32 h-32 bg-primary/10 rounded-full blur-xl" />

        <div className="container mx-auto px-4 py-12">
          {/* Hero Section */}
          <section className="relative mb-32">
            <FadeIn className="space-y-8" duration={0.7}>
              <motion.div
                initial={{ scale: 0.5, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ duration: 0.5 }}
                className="flex justify-center">
                <Badge className="rounded-full px-6 py-2 text-sm bg-primary text-primary-foreground">
                  ✨ Transform Images into Stories with AI
                </Badge>
              </motion.div>

              <div className="text-center space-y-6">
                <motion.h1
                  className="text-4xl sm:text-6xl lg:text-7xl font-bold tracking-tight"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.7, delay: 0.2 }}>
                  Turn Your Images Into
                  <motion.span
                    className="text-primary block mt-2"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.7, delay: 0.4 }}>
                    Captivating Stories
                  </motion.span>
                </motion.h1>

                <FadeIn delay={0.6}>
                  <p className="text-xl text-muted-foreground max-w-[700px] mx-auto">
                    Upload any image and watch as our AI transforms it into an
                    engaging story. Perfect for content creators, educators, and
                    storytellers.
                  </p>
                </FadeIn>

                <FadeIn delay={0.8} className="pt-4">
                  <div className="flex flex-wrap items-center justify-center gap-4">
                    <motion.div
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}>
                      <Link href="/generate-story">
                        <Button size="lg" className="rounded-full px-8">
                          Get Started <ArrowRight className="ml-2 h-4 w-4" />
                        </Button>
                      </Link>
                    </motion.div>
                    <motion.div
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}>
                      <Link href="/examples">
                        <Button
                          size="lg"
                          variant="outline"
                          className="rounded-full px-8">
                          View Examples
                        </Button>
                      </Link>
                    </motion.div>
                  </div>
                </FadeIn>
              </div>
            </FadeIn>
          </section>

          <section className="mb-32">
            <FadeIn className="text-center mb-16">
              {/* <Badge className="rounded-full px-6 py-2 text-sm bg-primary text-primary-foreground mb-6">
                Features
              </Badge> */}
              <h2 className="text-3xl font-bold mb-4">
                Why Choose Our Platform?
              </h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Discover how our AI-powered platform can transform your
                storytelling process
              </p>
            </FadeIn>

            <motion.div
              className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto"
              variants={{
                hidden: { opacity: 0 },
                show: {
                  opacity: 1,
                  transition: {
                    staggerChildren: 0.2,
                  },
                },
              }}
              initial="hidden"
              whileInView="show"
              viewport={{ once: true }}>
              {features.map((feature, index) => (
                <FeatureCard key={index} {...feature} />
              ))}
            </motion.div>
          </section>

          {/* How It Works Section */}
          <section className="mb-32">
            <FadeIn className="text-center mb-16">
              {/* <Badge className="rounded-full px-6 py-2 text-sm bg-primary text-primary-foreground mb-6">
                Process
              </Badge> */}
              <h2 className="text-3xl font-bold mb-4">How It Works</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Three simple steps to transform your images into engaging
                stories
              </p>
            </FadeIn>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto">
              <ProcessStep
                number={1}
                title="Upload Image"
                description="Drop or select any image you want to transform"
                icon={<ImageIcon className="h-6 w-6" />}
              />
              <ProcessStep
                number={2}
                title="AI Processing"
                description="Our AI analyzes and understands your image context"
                icon={<Wand2 className="h-6 w-6" />}
              />
              <ProcessStep
                number={3}
                title="Get Your Story"
                description="Receive a unique, engaging story based on your image"
                icon={<MessageSquareText className="h-6 w-6" />}
              />
            </div>
          </section>

          {/* Testimonials Section */}
          <section className="mb-32">
            <FadeIn className="text-center mb-16">
              {/* <Badge className="rounded-full px-6 py-2 text-sm bg-primary text-primary-foreground mb-6">
                Testimonials
              </Badge> */}
              <h2 className="text-3xl font-bold mb-4">What Our Users Say</h2>
              <p className="text-muted-foreground max-w-2xl mx-auto">
                Join thousands of satisfied users who are already using our
                platform
              </p>
            </FadeIn>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-6xl mx-auto">
              {testimonials.map((testimonial, index) => (
                <TestimonialCard key={index} {...testimonial} />
              ))}
            </div>
          </section>

          {/* FAQ Section */}
          <section className="mb-32">
            <FadeIn className="text-center mb-16">
              <h2 className="text-3xl font-bold mb-4">
                Frequently Asked Questions
              </h2>

              <p className="text-muted-foreground max-w-2xl mx-auto">
                Find answers to common questions about StorySnap
              </p>
            </FadeIn>

            <Accordion
              type="single"
              collapsible
              className="space-y-4 max-w-5xl mx-auto">
              {faqData.map((faq, index) => (
                <AccordionItem
                  key={index}
                  value={`item-${index}`}
                  className="border rounded-lg px-4">
                  <AccordionTrigger className="text-left text-lg font-semibold hover:no-underline">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground  pt-2 pb-4">
                    {faq.answer}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>

            <div className="text-center mt-8">
              <p className="text-muted-foreground">
                Still have questions?{" "}
                <a
                  href="mailto:support@ahaapple.com"
                  className="text-primary hover:underline font-medium">
                  Contact our support team
                </a>
              </p>
            </div>
          </section>

          {/* CTA Section */}
          <section>
            <Card className="relative overflow-hidden border-2 border-primary/20 bg-gradient-to-br from-primary/5 to-background">
              <CardContent className="p-12">
                <div className="max-w-3xl mx-auto text-center space-y-6">
                  <h2 className="text-3xl font-bold">
                    Ready to Start Your Story?
                  </h2>
                  <p className="text-muted-foreground">
                    Join thousands of creators who are already using our
                    platform to bring their images to life
                  </p>
                  <motion.div
                    className="z-10"
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}>
                    <Link href="/generate-story">
                      <Button size="lg" className="rounded-full px-8">
                        Get Started Now <ArrowRight className="ml-2 h-4 w-4" />
                      </Button>
                    </Link>
                  </motion.div>
                </div>
              </CardContent>
            </Card>
          </section>

          {/* Newsletter Signup */}
          {/* <section className="bg-muted py-12 mt-12">
            <div className="container mx-auto px-4 max-w-4xl text-center">
              <h3 className="text-2xl font-bold mb-4">
                Subscribe to Our Newsletter
              </h3>
              <p className="text-muted-foreground mb-6">
                Get the latest stories delivered to your inbox
              </p>
              <div className="flex gap-4 max-w-md mx-auto">
                <input
                  type="email"
                  placeholder="Enter your email"
                  className="flex-1 rounded-md border px-4 py-2"
                />
                <Button>Subscribe</Button>
              </div>
            </div>
          </section> */}
        </div>
      </div>
    </main>
  );
}
