export const testimonials = [
  {
    quote:
      "This tool has revolutionized how I create content for my blog. The stories it generates are incredibly engaging.",
    author: "Sarah Johnson",
    role: "Content Creator",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_1.png",
  },
  {
    quote:
      "As an educator, I use this daily to create engaging materials for my students. It's been a game-changer.",
    author: "Michael Chen",
    role: "Education Professional",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_2.png",
  },
  {
    quote:
      "The quality of the generated stories is consistently high. It saves me hours of work every week.",
    author: "Emma Davis",
    role: "Marketing Manager",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_3.png",
  },
  {
    quote:
      "StorySnap has transformed our social media strategy. The stories generated are perfect for engagement.",
    author: "David Wilson",
    role: "Social Media Manager",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_4.png",
  },
  {
    quote:
      "As a travel blogger, this tool helps me create compelling narratives for every destination photo.",
    author: "Lisa Zhang",
    role: "Travel Blogger",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_5.png",
  },
  {
    quote:
      "StorySnap has been a game-changer for our content strategy. The stories generated are always top-notch.",
    author: "Emily Nguyen",
    role: "Content Creator",
    avatar: "https://cdn.jsdelivr.net/gh/alohe/avatars/png/vibrent_6.png",
  },
];

export const faqData = [
  {
    question: "What is StorySnap?",
    answer:
      "StorySnap is an AI-powered platform that transforms your photos into engaging stories. Using advanced artificial intelligence, we help you create compelling narratives from your images with just a few clicks. Whether you're a content creator, business owner, or just someone who loves sharing stories, StorySnap makes it easy to bring your photos to life.",
  },
  {
    question: "How does StorySnap work?",
    answer:
      "Using StorySnap is simple: 1) Upload your photo to our platform. 2) Our AI analyzes your image and generates a unique story based on its contents. 3) Customize and edit the generated story to match your voice and style. 4) Share your story with your audience across various platforms. The entire process takes just minutes, and our AI ensures each story is unique and engaging.",
  },
  {
    question: "Is StorySnap free to use?",
    answer:
      "StorySnap offers both free and premium plans. With our free plan, you can create basic stories and access essential features. Our premium plans unlock advanced features like custom branding, higher resolution outputs, priority processing, and unlimited story generation. Visit our pricing page to learn more about our plans and choose the one that best fits your needs.",
  },
  {
    question: "What types of photos work best with StorySnap?",
    answer:
      "StorySnap works with virtually any type of photo, but the best results come from clear, high-quality images that tell a story or capture a moment. This could include travel photos, event pictures, product images, or personal memories. Our AI is trained to recognize and interpret a wide range of subjects, scenes, and emotions.",
  },
  {
    question: "Can I edit the stories generated by StorySnap?",
    answer:
      "Yes! While our AI creates compelling initial stories, you have full control over the final content. You can edit the text, adjust the tone, add personal details, and customize the story to perfectly match your vision. Our editor is user-friendly and includes features like tone adjustment, length control, and style customization.",
  },
  {
    question: "Can I use StorySnap for commercial purposes?",
    answer:
      "Yes! StorySnap offers commercial licenses for businesses. Our Enterprise plan includes features like bulk processing, API access, and white-labeling options. Contact our sales team for custom solutions tailored to your business needs.",
  },
  {
    question: "What languages does StorySnap support?",
    answer:
      "StorySnap currently supports 20+ languages including English, Spanish, French, German, Chinese, Japanese, and Korean. Our AI ensures natural-sounding narratives in each language, maintaining cultural context and nuances.",
  },
  {
    question: "How does StorySnap ensure content uniqueness?",
    answer:
      "Our AI generates unique stories for each image by analyzing multiple aspects including composition, colors, subjects, emotions, and context. Each story is cross-checked against our database to ensure originality.",
  },
];
export const homeConfig = {
  testimonials,
  faqData,
};
